theme: jekyll-theme-midnight
title: Dead Physicists Society
description: 
github:
  is_project_page: false
collections:
  workshops:
    output: true
defaults:
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"
  - scope:
      path: "/jayme"
    values:
      layout: "jayme"      
  - scope:
      path: ""
    values:
      layout: "default"
