theme: jekyll-theme-midnight
title: Dead Physicists Society
description: 
github:
  is_project_page: false
collections:
  workshops:
    output: true
defaults:
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop3"
  - scope:
      path: "jayme"
      type: "pages"
    values:
      layout: "jayme3"      
  - scope:
      path: ""
    values:
      layout: "default"
